deployment:
  replicas: 2
  image:
    owner: abdeod
    repository: todo-list-flask-app
    tag: 52506c97045fdb7de9debdc5f7e0e7d9a1d6e5fc
  container:
    name: todolist-app
    port: 80
service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30112
